sudo: false
language: node_js
node_js:
  - 10 # use nodejs v10 LTS
cache: npm
branches:
  only:
    - master # build master branch only
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $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
  keep-history: true
  on:
    branch: gh-pages
  local-dir: public
